add_newline=true
format="""
$git_status\
$git_branch\
$line_break\
$directory$character
"""
command_timeout=5000

[aws]
disabled=true

[battery]
disabled=true

[conda]
disabled=true

[crystal]
disabled=true

[cobol]
disabled=true

[dart]
disabled=true

[dotnet]
disabled=true

[elixir]
disabled=true

[elm]
disabled=true

[erlang]
disabled=true

[gcloud]
disabled=true

[git_status]
format='([\[$staged$conflicted$deleted$renamed$modified$untracked$ahead_behind\]]($style) )'
conflicted="C${count}"
ahead="⇡${count}"
deleted="D${count}"
modified="M${count}"
renamed="R${count}"
staged="S${count}"
untracked="U${count}"

[lua]
disabled=true

[golang]
disabled=true

[java]
disabled=true

[julia]
disabled=true

[kotlin]
disabled=true

[hg_branch]
disabled=true

[openstack]
disabled=true



[nim]
disabled=true

[nix_shell]
disabled=true

[nodejs]
disabled=true

[ocaml]
disabled=true

[package]
disabled=true

[perl]
disabled=true

[php]
disabled=true

[purescript]
disabled=true

[rlang]
disabled=true

[red]
disabled=true

[ruby]
disabled=true

[scala]
disabled=true

[singularity]
disabled=true

[vlang]
disabled=true

[vagrant]
disabled=true

[zig]
disabled=true
